version: '3'

services:
  app:
    container_name: fake_data_generator
    image: node:lts
    networks:
      - fdg
    working_dir: /usr/src/app
    ports:
      - 3333:3000
    volumes:
      - ./app:/usr/src/app
    command: npm run watch

networks:
  fdg:
   driver: bridge